#!/bin/bash

# Print disk layout
lsblk

# Prompt user for root location
read -p "Please enter root location to work on (example /dev/sda1): " DISK

# Install necessary packages with error handling
sudo pacman -S btrfs-progs snapper grub-btrfs --noconfirm --needed && yay -S btrfs-assistant btrfsmaintenance --noconfirm --needed
#sudo pacman -S btrfs-progs snapper grub-btrfs btrfs-assistant btrfsmaintenance --noconfirm --needed
#sudo pacman -S snap-pac --noconfirm

# Grub Snapshots
sudo systemctl enable grub-btrfsd.service && sudo systemctl start grub-btrfsd.service

# Remove existing .snapshots directories
sudo umount /.snapshots
sudo rm -rf /.snapshots

# Configure snapper for root with sed
sudo snapper -c root create-config /
sudo sed -i 's/^ALLOW_USERS=""/ALLOW_USERS="howling"/' /etc/snapper/configs/root
sudo sed -i 's/^TIMELINE_LIMIT_HOURLY="10"/TIMELINE_LIMIT_HOURLY="0"/' /etc/snapper/configs/root
sudo sed -i 's/^TIMELINE_LIMIT_DAILY="10"/TIMELINE_LIMIT_DAILY="4"/' /etc/snapper/configs/root
sudo sed -i 's/^TIMELINE_LIMIT_WEEKLY="0"/TIMELINE_LIMIT_WEEKLY="2"/' /etc/snapper/configs/root
sudo sed -i 's/^TIMELINE_LIMIT_MONTHLY="10"/TIMELINE_LIMIT_MONTHLY="1"/' /etc/snapper/configs/root
sudo sed -i 's/^TIMELINE_LIMIT_YEARLY="10"/TIMELINE_LIMIT_YEARLY="0"/' /etc/snapper/configs/root
sudo btrfs subvolume delete /.snapshots
sudo mkdir -p /.snapshots
sudo mkdir -p /mnt/btrfs

# Mount disk
sudo mount "${DISK}" /mnt/btrfs || exit 1

# Create subvolume for snapshots
sudo btrfs subvolume delete /mnt/btrfs/@.snapshots
sudo btrfs subvolume create /mnt/btrfs/snapshots
sudo chmod a+rx /.snapshots
sudo chown :howling /.snapshots
sudo umount /mnt/btrfs
sudo rmdir /mnt/btrfs
sudo chattr +C /.snapshots

# Add entry to /etc/fstab
#replace uuid from id u get fromm /etc/fstab
PART_UUID=$(sudo blkid -o value -s UUID "${DISK}")
echo "UUID=${PART_UUID} /.snapshots    btrfs defaults,ssd,discard,noatime,compress=no,space_cache=v2,subvol=snapshots 0 0" | sudo tee -a /etc/fstab > /dev/null || exit 1

# Mount all filesystems from /etc/fstab
sudo mount -a

# snap
echo "first manual snapshot"
sudo snapper -c root create --description "initial snapshot"
sleep 1
sudo grub-mkconfig -o /boot/grub/grub.cfg


