[[manager.prepend_keymap]]
on   = [ "`", "a" ]
run  = "plugin compress"
desc = "Archive selected files"

[[manager.prepend_keymap]]
on   = [ "`", "m" ]
run = "plugin mount"
desc = "Mount"

[[manager.prepend_keymap]]
on  = ["`", "s"]
run = "plugin what-size"
desc = "Show file size"

[[manager.prepend_keymap]]
on = ["g", "D"]
run = "cd ~/Media/D"
desc = "D"

[[manager.prepend_keymap]]
on = ["g", "E"]
run = "cd ~/Media/E"
desc = "E"

[[manager.prepend_keymap]]
on = ["g", "o"]
run = "cd ~/.othercrap"

[[manager.prepend_keymap]]
on = ["g", "v"]
run = "cd ~/Videos"

[[manager.prepend_keymap]]
on = ["g", "m"]
run = "cd ~/Media"

[[manager.prepend_keymap]]
on   = "<Enter>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = ["c", "a"]
run = ["plugin copy-file-contents"]
desc = "Copy contents of file"

[[manager.prepend_keymap]]
on = ["C", "b"]
run = ["shell --block 'nvim ~/.bashrc'"]
desc = ".bashrc config"

[[manager.prepend_keymap]]
on = ["C", "k"]
run = ["shell --block 'nvim ~/.config/kitty/kitty.conf'"]
desc = "kitty config"

[[manager.prepend_keymap]]
on = ["C", "y"]
run = ["shell --block 'nvim ~/.config/yazi/keymap.toml'"]
desc = "yazi keymap config"

[[manager.prepend_keymap]]
on = ["C", "p"]
run = ["shell --block 'nvim ~/.config/polybar/config.ini'"]
desc = "polybar config"

[[manager.prepend_keymap]]
on = ["C", "i"]
run = ["shell --block 'nvim ~/.config/i3/config'"]
desc = "i3 config"

[[manager.prepend_keymap]]
on = ["C", "m"]
run = ["shell --block 'nvim ~/.config/mpv/mpv.conf'"]
desc = "mpv config"

[[manager.prepend_keymap]]
on = ["g", "s"]
run = "cd /usr/local/bin"
desc = "Scripts"

[[manager.prepend_keymap]]
on = ["g", "p"]
run = "cd ~/Pictures"
desc = "Pictures"

[[manager.prepend_keymap]]
on = ["`", "d"]
run = "shell 'dragon-drop -a -x $@'"
desc = "Dragon"

[[manager.prepend_keymap]]
on = ["`", "D"]
run = "shell 'dlfile &'"
desc = "Dragon Save"
