#!/bin/bash

menu() {
    echo "Choose an option:"
    echo "1. Convert all *.mp4 to .mkv in the folder"
    echo "2. Combine a video.mp4 and audio.mp4 to mkv"
    echo "3. Combine a video.mp4 and audio.mp4 and subtitle.srt to mkv"
    echo "4. Combine all Mkv in a folder with Subtitle.st"
    echo "5. Fix Flac"
    echo "0. Exit"
    read -p "Enter your choice (0-5): " choice

    case "$choice" in
        1)
            for f in *.mp4; do
                mkvmerge -o "${f%.mp4}.mkv" "$f"
            done
            ;;
        2)
            mkvmerge -o 2024.1080p.WEB-DL.AAC2.0.H.264-Cy.mkv video.mp4 -a 0 -d 0 audio.mp4
            ;;
        3)
            mkvmerge -o 2024.1080p.WEB-DL.AAC2.0.H.264-Cy.mkv video.mp4 -a 0 -d 0 audio.mp4 --subtitle-tracks 0 --language 0:eng subtitle.srt
            ;;
        4)
            for f in *.mkv; do
                mkvmerge -o "${f%.mkv}_with_subtitle.mkv" "$f" --language 0:eng subtitle.srt
            done
            ;;
        5)
            flac -f8 *.flac
            flac --best --verify --force --padding=4096 *.flac
            ;;
        0)
            exit 0
            ;;
        *)
            echo "Invalid choice. Please try again."
            ;;
    esac

    # Play the sound using mpg123
    mpg123 ~/.othercrap/1.mp3

    menu
}

menu
