#! /bin/bash
sudo btrfs subvolume delete /.snapshots
sudo mkdir /.snapshots
sudo mkdir /mnt/btrfs
sudo mount /dev/sda2 /mnt/btrfs
sudo btrfs subvolume create /mnt/btrfs/snapshots
sudo chmod a+rx /.snapshots/
sudo umount /mnt/btrfs
sudo bash -c 'echo "UUID=cb4d77df-3e6a-4179-a881-df7c85f4b7c9 .snapshots     btrfs   subvol=snapshots 0 0" >> /etc/fstab'
sudo btrfs subvolume get-default /
sudo btrfs subvolume set-default 256 /
#sudo nano /boot/grub/grub.cfg
#removeall = rootflags=subvol=@  
#sudo snapper rollback 2
#sudo snapper --ambit classic rollback 2

#sudo snapper -c root create-config / 
#snapper status 21..22
#sudo btrfs subvolume list /
#snapper list
#snapper delete
#snapper diff 71..72 /etc/zypp/zypp.conf
#snapper create --description "Snapshot for week 2 2014"
#sudo snapper --ambit classic rollback 2
