#! /bin/bash
tput setaf 1; echo -----ERRORS FOR "$1" SEND TO ~/checkerror.txt----                     
tput sgr0; echo   ---------ERRORS FOR "$1"------------ >~/checkerror.txt
echo "" >~/checkerror.txt
sleep 1
bash "$1" 2>~/checkerror.txt
