#!/bin/bash

# Print disk layout
lsblk

# Prompt user for root location
read -p "Please enter root location to work on (example /dev/sda1): " DISK

# Install necessary packages with error handling
sudo pacman -S snapper --noconfirm --needed
yay -S btrfs-assistant --noconfirm --needed
sudo pacman -S grub-btrfs --noconfirm --needed
sudo pacman -S snap-pac --noconfirm --needed

# Remove existing .snapshots directories
sudo umount /.snapshots
sudo rm -rf /.snapshots

# Configure snapper for root with sed
sudo snapper -c root create-config /
sudo sed -i 's/^ALLOW_USERS=""/ALLOW_USERS="howling"/' /etc/snapper/configs/root
sudo sed -i 's/^TIMELINE_LIMIT_HOURLY="10"/TIMELINE_LIMIT_HOURLY="0"/' /etc/snapper/configs/root
sudo sed -i 's/^TIMELINE_LIMIT_DAILY="10"/TIMELINE_LIMIT_DAILY="7"/' /etc/snapper/configs/root
sudo sed -i 's/^TIMELINE_LIMIT_WEEKLY="0"/TIMELINE_LIMIT_WEEKLY="2"/' /etc/snapper/configs/root
sudo sed -i 's/^TIMELINE_LIMIT_MONTHLY="10"/TIMELINE_LIMIT_MONTHLY="2"/' /etc/snapper/configs/root
sudo sed -i 's/^TIMELINE_LIMIT_YEARLY="10"/TIMELINE_LIMIT_YEARLY="0"/' /etc/snapper/configs/root
sudo btrfs subvolume delete /.snapshots
sudo mkdir -p /.snapshots
sudo mkdir -p /mnt/btrfs

# Mount disk
sudo mount "${DISK}" /mnt/btrfs || exit 1

# Create subvolume for snapshots
sudo btrfs subvolume create /mnt/btrfs/snapshots
sudo chmod a+rx /.snapshots
sudo chown howling:howling /.snapshots
sudo umount /mnt/btrfs
sudo rmdir /mnt/btrfs

# Add entry to /etc/fstab
#replace uuid from id u get fromm /etc/fstab
PART_UUID=$(sudo blkid -o value -s UUID "${DISK}")
echo "UUID=${PART_UUID} /.snapshots    btrfs rw,defaults,subvol=snapshots 0 0" | sudo tee -a /etc/fstab > /dev/null || exit 1

# Mount all filesystems from /etc/fstab
sudo mount -a

# snap
echo "first manual snapshot"
sudo snapper -c root create --description "initial snapshot"
#btrfs subvolume get-default /
# sudo btrfs subv list / get the id of root
#btrfs subvolume set-default 256 /
#btrfs subvolume get-default /
#sed -i 's/rootflags=subvol=@  //g' /boot/grub/grub.cfg
#sudo nano /boot/grub/grub.cfg
#removeall = rootflags=subvol=@  
#sudo snapper rollback 2
#sudo snapper --ambit classic rollback 2
#sudo snapper -c root create-config / 
#snapper status 21..22
#sudo btrfs subvolume list /
#snapper list
#snapper delete
#snapper diff 71..72 /etc/zypp/zypp.conf
#snapper undochange 1..2
#snapper create --description "Snapshot for week 2 2014"
#sudo snapper -c boot delete-config
#sudo snapper -c boot create-config /boot  
#sudo snapper -c boot create --description "1" 
#sudo chmod a+rx /boot/.snapshots  
